### ISSUE TITLE
Add new video suits

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-suites#6]
I would like to propose the addition of the following test suits:

**AV1**
- dav1d
- aom-av1
- svt-av1

**Video encoding**
- aom-av1
- vpxenc
- x264
- x265
- svt-av1
- svt-hevc
- svt-vp9

**Comment by EwoutH** [comment]
@michaellarabel What do you think?

**Comment by EwoutH** [comment]
@michaellarabel Any comment?

**Comment by michaellarabel** [comment]
Yes I can add such a suite when time permits, hopefully in the next few days.

**Comment by EwoutH** [comment]
I see that there is already a _video-encoding_ suite, so it only has to be a new AV1 suite with dav1d, aom-av1 and svt-av1.

**Comment by michaellarabel** [comment]
There is now an AV1 suite [ https://openbenchmarking.org/suite/pts/av1 ]

The existing video-encoding suite has been updated to include the missing tests and also including the AV1 suite (effectively a sub-suite) to provide all AV1 tests going forward. [ https://openbenchmarking.org/suite/pts/video-encoding  ]

**Comment by EwoutH** [comment]
Technically dav1d isn't an encoder, but fine by me. :)

Thanks!
